### PR TITLE
Use binaries in JuliaBinaryWrappers

### PR DESCRIPTION
**Pull request by giordano**
This won't work on Windows, but at least pass on macOS

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Cool, what's the problem on Windows?

**Comment by SimonDanisch** [comment]
Lol, libuuid... I forgot :D

**Comment by giordano** [comment]
Windows with Julia 1.2 is working now :slightly_smiling_face:  (Julia nightly on Windows Travis looks broken)

**Comment by giordano** [comment]
Bump 🙂

**Comment by SimonDanisch** [comment]
Awesome!! :) Thank you so much!

**Pull request merged**
