### PR TITLE
switch to binarybuilder

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
@giordano, so I see that there is no windows build for fontconfig... How does that work for Cairo?

**Comment by giordano** [comment]
Pango doesn't require Fontconfig on macOS and Windows and we're not using it.  The showstopper is libuuid (which is required by Fontconfig), I can't find a libuuid that can be cross-compiled for Windows.  I opened an issue on util-linux (https://github.com/karelzak/util-linux/issues/853), but their suggestion doesn't work for me (with `make libuuid.la` it does try to compile, but it fails on some Unix-only header), but I don't have the time now to investigate further.

**Comment by giordano** [comment]
Why closed? 🤔

**Comment by SimonDanisch** [comment]
Ahhhh didn't realize you didn't make your PR against master :D

**Comment by giordano** [comment]
Yes, I should have done so 😬

**Comment by SimonDanisch** [comment]
Was just starting to wonder, how the hell you tested on windows in travis, without having that change show up in the travis file on master after the merge :D

**Pull request merged**
